server:
  port: 9090


spring:
  data:
    mongodb:
      database: test-distributed-systems
      uri: mongodb+srv://aneeta:DIHEinstitute2@cluster0.sq9cc.mongodb.net/distributed-systems?retryWrites=true&w=majority
      auto-index-creation: true


app:
  configs:
    broker:
      activemq:
        url: "failover://tcp://localhost:61616"
        username: "admin"
        password: "password"
    heartbeat:
      interval: 100000
      endpoint: /actuator/health
      protocol: http